## Install Numpy

In [1]:
!pip3 install numpy

## Import Numpy

In [2]:
import numpy as np

## Array 1 Dimensi

In [3]:
arr1 = np.array([1, 2, 3])

In [4]:
print(arr1)

[1 2 3]


In [5]:
arr1

array([1, 2, 3])

In [6]:
arr1[1]

2

In [7]:
arr1.shape

(3,)

In [8]:
arr1.reshape(3,1)

array([[1],
       [2],
       [3]])

## Array 2 Dimensi

In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2[1,1]

5

In [13]:
arr2.shape

(2, 3)

In [15]:
arr2.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Delete Element

In [29]:
arr = np.array([1, 2, 3, 4, 5])

In [19]:
arr

array([1, 2, 3, 4, 5])

In [26]:
np.delete(arr, 1, 0)

array([[1, 2, 3, 4]])

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6])

In [56]:
np.delete(arr, 0, 0)

array([[4, 5, 6]])

In [57]:
np.delete(arr, 1, 1)

array([[1, 3],
       [4, 6]])

## Create Empty Array

In [40]:
np.empty([2,2], dtype=int)

array([[0, 0],
       [0, 0]])