<!-- <a href="https://colab.research.google.com/github/rubythalib33/Sekolah-AI-Indonesia/blob/main/Course%201.%20Pytorch%2BLightning%20Coureses%20Level%201/1_2_ANN_training_with_dummy_datasets_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> -->

# 1.2 ANN training with dummy datasets

Syllabus:
1. create a linear function for the dummy datasets
2. create dummy datasets
3. create model
4. create training scheme
5. create inference function

## 1. create a linear function for the dummy datasets

for this tutorial we are gonna make this function for the datasets,
f(x1,x2,x3,x4) = x1*w1+x2*w2+x3*w3+x4*w4
w1 = 1
w2 = 2
w3 = 3
w4 = 4

In [1]:
def function(x1, x2, x3, x4):
  w1,w2,w3,w4 = 1,2,3,4
  return  x1*w1+x2*w2+x3*w3+x4*w4

In [2]:
#example
x1,x2,x3,x4 = 1,2,3,4
function(x1,x2,x3,x4) #1+4+9+16=30

30

## 2. create dummy datasets


In [3]:
import numpy as np

In [4]:
def create_dummy_datasets(n=1000):
  x = np.random.randint(0, 2000, size=(n,4))

  y = []
  for i in x:
    y_temp = function(*i) #i[0], i[1], ..., i[n-1] n: panjang arraynya
    y.append(y_temp)
  
  y = np.asarray(y)

  return x,y

In [5]:
N_SAMPLE = 1000
data = create_dummy_datasets(N_SAMPLE)

In [6]:
print(data[0]) #for the x data
print(data[1]) #for the y data

[[ 699 1803  639    6]
 [ 633 1165  123  432]
 [1426 1842  394 1987]
 ...
 [ 220 1617 1331  821]
 [ 924 1755 1645 1024]
 [ 944 1284 1597 1758]]
[ 6246  5060 14240 13979 14728 12767  6788  8160 13568  8886 11440  9908
 13330 13814  9982 13669 10070  9655  8275 13616 10066 10118  4328 10146
  9958 10095 12463  6887 13560 10451 10966  4983 13788 10580 13993 11652
 10139  2873  8569  9543 14991 10881  9226 12944  8684  6375  7863 12363
  9830  1359 14780  4945 12776  8431  7897  5714  4917 14795 12380  9830
  5718 13422  5829 13533  7185 16257 14231 10762 13599  7330  8871  4978
  9944 11362  9031  8005 16481  7542 11400 11099  5799 10606  5337 10185
 10405 13541 11256 14335 12617  7851  6175 10660  8416  9431  4401 13282
  9945  5702  6762 17968 11929 14185  4929  7174  9181 13716 13737  5040
  7752  7987  7776  9801  6707  8824  6795 11446 10566 11944  7672  9963
 14692 13224  4663 12750  9231  5688 11021  9544 12113  1939  9165 13520
  6903 12519 11352  6376  5169 12601 14453 10503 1460

In [7]:
#lets convert it to torch.tensor dtype torch.float32 so it can run smoothly on neural nets
import torch

In [8]:
X = torch.tensor(data[0], dtype = torch.float32)
y = torch.tensor(data[1], dtype = torch.float32)

In [9]:
print(X)
print(y)

tensor([[ 699., 1803.,  639.,    6.],
        [ 633., 1165.,  123.,  432.],
        [1426., 1842.,  394., 1987.],
        ...,
        [ 220., 1617., 1331.,  821.],
        [ 924., 1755., 1645., 1024.],
        [ 944., 1284., 1597., 1758.]])
tensor([ 6246.,  5060., 14240., 13979., 14728., 12767.,  6788.,  8160., 13568.,
         8886., 11440.,  9908., 13330., 13814.,  9982., 13669., 10070.,  9655.,
         8275., 13616., 10066., 10118.,  4328., 10146.,  9958., 10095., 12463.,
         6887., 13560., 10451., 10966.,  4983., 13788., 10580., 13993., 11652.,
        10139.,  2873.,  8569.,  9543., 14991., 10881.,  9226., 12944.,  8684.,
         6375.,  7863., 12363.,  9830.,  1359., 14780.,  4945., 12776.,  8431.,
         7897.,  5714.,  4917., 14795., 12380.,  9830.,  5718., 13422.,  5829.,
        13533.,  7185., 16257., 14231., 10762., 13599.,  7330.,  8871.,  4978.,
         9944., 11362.,  9031.,  8005., 16481.,  7542., 11400., 11099.,  5799.,
        10606.,  5337., 10185., 10405.

## 3.lets build a model

In [10]:
from torch import nn

In [11]:
class RegressionModel(nn.Module):
  def __init__(self, input_node=4, output_node=1):
    super().__init__()
    self.input_node = input_node
    self.output_node = output_node

    self.fc = nn.Linear(self.input_node, self.output_node, bias=False) #we want to make the bias false so it can relate with the function but in most cases you need the bias to be true
  
  def forward(self,x):
    return self.fc(x)

## 4. Let's Create training scheme
before that let's understand about concept of optimization and loss function

In [12]:
sample_model = RegressionModel()
optim = torch.optim.SGD(sample_model.parameters(), lr=0.001) #Stochastic Gradient Descent
loss_fn = nn.MSELoss() #Mean Squared error loss

In [13]:
sample_X = X
sample_y = y

BATCH_SIZE = 10
sample_X = torch.reshape(sample_X, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4)) #let's make batch 10 | (N_SAMPLE,4) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4) -> (100, 10, 4)
sample_y = torch.reshape(sample_y, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1)) #let's make batch 10 | (N_SAMPLE,1) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1) -> (100, 10, 1)

sample_X = sample_X/2000
sample_y = sample_y/2000

In [14]:
print(sample_X.shape)
print(sample_y.shape)
print(sample_model)

torch.Size([100, 10, 4])
torch.Size([100, 10, 1])
RegressionModel(
  (fc): Linear(in_features=4, out_features=1, bias=False)
)


In [15]:
#this is what we call one epoch training
for i in range(1000):
  print("EPOCH ", i)
  for i, (inputs, target) in enumerate(zip(sample_X, sample_y)):
    output = sample_model(inputs)
    loss = loss_fn(output,target)
    if i % 10 == 0:
      print("   step ",i)
      print(loss.item())
    # Backpropagation
    optim.zero_grad()
    loss.backward()
    optim.step()

EPOCH  0
   step  0
34.074546813964844
   step  10
27.48941993713379
   step  20
32.15805435180664
   step  30
24.9810733795166
   step  40
25.606586456298828
   step  50
18.701845169067383
   step  60
29.220190048217773
   step  70
22.25752830505371
   step  80
23.027238845825195
   step  90
19.659114837646484
EPOCH  1
   step  0
22.019094467163086
   step  10
17.484846115112305
   step  20
20.938106536865234
   step  30
16.02000617980957
   step  40
16.467050552368164
   step  50
12.346586227416992
   step  60
19.545955657958984
   step  70
14.358922004699707
   step  80
14.534258842468262
   step  90
12.464616775512695
EPOCH  2
   step  0
14.260087966918945
   step  10
11.104805946350098
   step  20
13.700662612915039
   step  30
10.28873348236084
   step  40
10.619315147399902
   step  50
8.223793029785156
   step  60
13.198115348815918
   step  70
9.296991348266602
   step  80
9.151324272155762
   step  90
7.903729438781738
EPOCH  3
   step  0
9.263871192932129
   step  10
7.04300

In [16]:
#lets see the total loss
loss_total = []
for inputs, target in zip(sample_X, sample_y):
  output = sample_model(inputs)
  loss = loss_fn(output,target)
  loss_total.append(loss.item())

loss_average = np.mean(loss_total)

In [17]:
print(loss_average)

4.592804538905426e-09


In [18]:
#lets we see the parameters, that's the weight that we trained
for param in sample_model.parameters():
  print(param.data)

tensor([[1.0001, 2.0001, 2.9999, 3.9999]])


## 5. create inference function

In [19]:
def inference(x1,x2,x3,x4):
  inputs = torch.tensor([[x1,x2,x3,x4]], dtype=torch.float32)
  inputs = inputs/2000
  output = sample_model(inputs)
  output*=2000

  return output[0].detach().numpy()

In [20]:
x1,x2,x3,x4 = 3,4,5,6
inference(x1,x2,x3,x4), function(x1,x2,x3,x4)

(array([49.999325], dtype=float32), 50)