In [48]:
# def function(x1, x2, x3, x4):
#     w1, w2, w3, w4 = 1, 2, 3, 4
#     return x1*w1+x2*w2+x3*w3+x4*w4

def function(x1, x2, x3, x4):
  w1,w2,w3,w4 = 1,2,3,4
  return  x1*w1+x2*w2+x3*w3+x4*w4

In [49]:
x1, x2, x3, x4 = 1, 2, 3, 4
function(x1, x2, x3, x4)

30

In [50]:
import numpy as np

In [51]:
# def create_dummy_datasets(n=1000):
#     x = np.random.randint(0, 2000, size=(n, 4))

#     y = []
#     for i in x:
#         y_temp = function(*i)
#         y.append(y_temp)

#     y = np.asarray(y_temp)

#     return x, y

def create_dummy_datasets(n=1000):
  x = np.random.randint(0, 2000, size=(n,4))

  y = []
  for i in x:
    y_temp = function(*i) #i[0], i[1], ..., i[n-1] n: panjang arraynya
    y.append(y_temp)
  
  y = np.asarray(y)

  return x,y

In [52]:
N_SAMPLE = 1000
data = create_dummy_datasets(N_SAMPLE)

In [53]:
print(data[0])
print(data[1])

[[1412  575  809 1671]
 [ 791 1918 1495 1383]
 [ 407  716 1244  137]
 ...
 [ 839 1039 1562 1907]
 [ 646  577 1669   46]
 [ 683 1261 1393 1723]]
[11673 14644  6119  3677  6334  9414  9686 10137 12882  8014  9741  4816
  7786 10019  8619 12967 13223 12735  8826  8259 12807  7113  8213  6335
  6162 17847 13069 12153 14605  4296  8648  6731 11099  5058 13954  4159
  9918  6456 16156 13658  8302 11780  9037 14344  4841  6966  4500  9023
 10509 11485 14454 10272  5993 10082  8621 11280  9209  8286 16982  7077
  7838 12340 13667 12990  9828 11536  8324  8355 11691  9913  8485  9333
 15520 11683 15897  5439 13681  7962 10946 10824 10262  9402 11584 14966
  9570 11845 11963  8902  9334  8706  6442 12615  8619 12104 12694  8989
  9889 11211  4248 10828 15194 12738  5887  7946 14038  7111  9325  4984
 11773 10709 13677 12747  7939  9936  7147  5334 12692 13964 14107 15052
 13520 12201 12883 10723 15357  9686 11438 13130  7911 12494  9407  8789
 10495 15707  9050  5391 10364  8838  8368 10603 1438

In [54]:
import torch

In [55]:
# X = torch.tensor(data[0], dtype= torch.float32)
# y = torch.tensor(data[1], dtype= torch.float32)

X = torch.tensor(data[0], dtype = torch.float32)
y = torch.tensor(data[1], dtype = torch.float32)

In [56]:
print(X)
print(y)

tensor([[1412.,  575.,  809., 1671.],
        [ 791., 1918., 1495., 1383.],
        [ 407.,  716., 1244.,  137.],
        ...,
        [ 839., 1039., 1562., 1907.],
        [ 646.,  577., 1669.,   46.],
        [ 683., 1261., 1393., 1723.]])
tensor([11673., 14644.,  6119.,  3677.,  6334.,  9414.,  9686., 10137., 12882.,
         8014.,  9741.,  4816.,  7786., 10019.,  8619., 12967., 13223., 12735.,
         8826.,  8259., 12807.,  7113.,  8213.,  6335.,  6162., 17847., 13069.,
        12153., 14605.,  4296.,  8648.,  6731., 11099.,  5058., 13954.,  4159.,
         9918.,  6456., 16156., 13658.,  8302., 11780.,  9037., 14344.,  4841.,
         6966.,  4500.,  9023., 10509., 11485., 14454., 10272.,  5993., 10082.,
         8621., 11280.,  9209.,  8286., 16982.,  7077.,  7838., 12340., 13667.,
        12990.,  9828., 11536.,  8324.,  8355., 11691.,  9913.,  8485.,  9333.,
        15520., 11683., 15897.,  5439., 13681.,  7962., 10946., 10824., 10262.,
         9402., 11584., 14966.,  9570.

# Build Model

In [57]:
from torch import nn

In [58]:
# class RegressionModel(nn.Module):
#     def __init__(self, input_node=4, output_node=1):
#         super().__init__()
#         self.input_node = input_node
#         self.output_node = output_node

#         self.fc = nn.Linear(self.input_node, self.output_node, bias=True)

#     def forward(self, x):
#         return self.fc(x)

class RegressionModel(nn.Module):
  def __init__(self, input_node=4, output_node=1):
    super().__init__()
    self.input_node = input_node
    self.output_node = output_node

    self.fc = nn.Linear(self.input_node, self.output_node, bias=False) #we want to make the bias false so it can relate with the function but in most cases you need the bias to be true
  
  def forward(self,x):
    return self.fc(x)

# Create Traiing Scheme

In [59]:
# sample_model = RegressionModel()
# optim = torch.optim.SGD(sample_model.parameters(), lr=0.001)
# loss_fn = nn.MSELoss()

sample_model = RegressionModel()
optim = torch.optim.SGD(sample_model.parameters(), lr=0.001) #Stochastic Gradient Descent
loss_fn = nn.MSELoss()

In [60]:
sample_X = X
sample_y = y

# sample_X.shape
# sample_y.shape
BATCH_SIZE = 10
sample_X = torch.reshape(sample_X, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4)) #let's make batch 10 | (N_SAMPLE,4) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 4) -> (100, 10, 4)
sample_y = torch.reshape(sample_y, (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1)) #let's make batch 10 | (N_SAMPLE,1) -> (N_SAMPLE//BATCH_SIZE, BATCH_SIZE, 1) -> (100, 10, 1)

sample_X = sample_X/2000
sample_y = sample_y/2000

In [61]:
print(sample_X.shape)
print(sample_y.shape)
print(sample_model)

torch.Size([100, 10, 4])
torch.Size([100, 10, 1])
RegressionModel(
  (fc): Linear(in_features=4, out_features=1, bias=False)
)


In [62]:
for i in range(1000):
    print('EPOCH', i)
    for i, (inputs, target) in enumerate(zip(sample_X, sample_y)):
        output = sample_model(inputs)
        loss = loss_fn(output, target)
        if i % 10 == 0:
            print("   step ", i)
            print(loss.item())

        optim.zero_grad()
        loss.backward()
        optim.step()

EPOCH 0
   step  0
29.35455322265625
   step  10
30.475994110107422
   step  20
37.96016311645508
   step  30
24.98720359802246
   step  40
26.17342758178711
   step  50
40.02668762207031
   step  60
20.105825424194336
   step  70
24.407630920410156
   step  80
20.686084747314453
   step  90
14.071981430053711
EPOCH 1
   step  0
18.68829917907715
   step  10
19.87725257873535
   step  20
24.622873306274414
   step  30
16.21215057373047
   step  40
16.951045989990234
   step  50
26.23031234741211
   step  60
12.978129386901855
   step  70
15.937952041625977
   step  80
13.4314546585083
   step  90
9.104537963867188
EPOCH 2
   step  0
11.874080657958984
   step  10
13.013964653015137
   step  20
16.002660751342773
   step  30
10.542037963867188
   step  40
10.996368408203125
   step  50
17.2512149810791
   step  60
8.406301498413086
   step  70
10.448537826538086
   step  80
8.749063491821289
   step  90
5.9133758544921875
EPOCH 3
   step  0
7.5306715965271
   step  10
8.565547943115234


In [63]:
loss_total = []
for inputs, target in zip(sample_X,sample_y):
    output = sample_model(inputs)
    loss = loss_fn(output, target)
    loss_total.append(loss.item())

loss_average = np.mean(loss_total)

In [64]:
print(loss_average)

6.7144664472884585e-09


In [65]:
for param in sample_model.parameters():
    print(param.data)

tensor([[1.0001, 2.0002, 2.9998, 3.9999]])


# Create Inference Function

In [66]:
def inference(x1,x2,x3,x4):
    inputs = torch.tensor([[x1, x2, x3, x4]], dtype= torch.float32)
    inputs = inputs/2000
    output = sample_model(inputs)
    output*=2000

    return output[0].detach().numpy()

In [67]:
x1, x2, x3, x4 = 3, 4, 5, 6
inference(x1, x2, x3, x4), function(x1, x2, x3, x4)

(array([49.999413], dtype=float32), 50)

In [68]:
h = 50 - 49.999413
print(h)

0.0005870000000030018
