# Array

In [11]:
import numpy as np

In [12]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [13]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
a = [1,2,3,4,]
b = [5,6,7,8,]

type(a), type(b)

(list, list)

In [15]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [16]:
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [17]:
arrayA = np.array(a)
arrayB = np.array(b)

type(arrayA), type(arrayB)

(numpy.ndarray, numpy.ndarray)

In [18]:
arrayA * arrayB

array([ 5, 12, 21, 32])

In [19]:
arrayA / arrayB

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [20]:
arrayB * 5

array([25, 30, 35, 40])

In [22]:
y_pred = np.array([1, 1, 0, 1, 1, 0, 1, 1])
labels = np.array([0, 1, 0, 1, 1, 0, 1, 1])

mse = (1/len(labels)) * np.sum(np.square(y_pred - labels))
print(mse)

0.125


# Array 1D

In [23]:
arr = np.array(42)

In [24]:
print(arr)

42


## Array 2D

In [25]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
print(arr)

[[1 2 3]
 [4 5 6]]


## Array 3D

In [27]:
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
])

In [28]:
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


## Array 3D

In [29]:
arr = np.array([[
    [1, 2, 3], [4, 5, 6],
    [7, 8, 9], [10, 11, 12]
]])

In [30]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [31]:
arr = np.zeros(5)

In [32]:
print(arr)

[0. 0. 0. 0. 0.]


In [34]:
arr = np.zeros((5,2))

In [35]:
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [36]:
arr = np.ones((7,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [37]:
arr = np.ones((3,4,2))
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [38]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

arr = np.delete(arr, 1, axis=0)

print(arr)

[[1 2 3]
 [7 8 9]]


In [39]:
del arr

In [40]:
arr

NameError: name 'arr' is not defined

## Mengakses Elemen pada Numpy Array

In [41]:
arr = np.array([1, 2, 3, 4, 5])

In [42]:
arr[1]

2

In [43]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

In [44]:
print(arr[1, 4])

10


In [45]:
print(arr[1, -1])

10


In [46]:
print(arr[1, 1:4])

[7 8 9]


## Mengecek Tipe Data Pada Numpy Array

In [47]:
arr = np.array([1, 2, 3, 4, 5])

In [48]:
print(arr.dtype)

int32


In [49]:
arr = np.array([1.2, 2, 3, 4, 5])

In [50]:
print(arr.dtype)

float64


In [51]:
arr = np.array([1, 2, 3, 4, 5], dtype='S')

In [52]:
print(arr)

[b'1' b'2' b'3' b'4' b'5']


In [53]:
print(arr.dtype)

|S1


In [54]:
arr[0]

b'1'

In [55]:
arr = np.array([1, 2, 3, 4, 5], dtype='I')

In [56]:
print(arr)

[1 2 3 4 5]


In [57]:
print(arr.dtype)

uint32


In [58]:
arr = np.array([1.2, 2.3, 3.3])

In [59]:
arr = arr.astype('i')

In [60]:
arr

array([1, 2, 3], dtype=int32)

In [61]:
print(arr.dtype)

int32


## Fungsi Arange

In [62]:
arr = np.arange(10)

In [63]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
print(type(arr))

<class 'numpy.ndarray'>


In [66]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [67]:
arr = np.arange(10, 20)

In [68]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [69]:
arr = np.arange(-1, 1, 0.1)
arr

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])