## Mendapatkan shape dari Array

In [18]:
import numpy as np

In [19]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [20]:
print(arr.shape)

(2, 4)


In [21]:
print(arr.size)

8


In [22]:
print(arr.ndim)

2


## Meenggunakanan ndim untuk mendefinisikan demensi

In [23]:
arr = np.array([1, 2, 3, 4, 5,], ndmin=3)

In [24]:
print(arr)

[[[1 2 3 4 5]]]


In [25]:
print(arr.shape)

(1, 1, 5)


In [26]:
print(arr.ndim)

3


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [29]:
arr.shape

(12,)

In [30]:
arr = arr.reshape(4, 3)

In [31]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
arr.ndim

2

## Reshape dari 1D ke 3D

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [35]:
arr = arr.reshape(2, 3, 2)

In [36]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [37]:
arr.ndim

3

In [38]:
arr.shape

(2, 3, 2)

## Menggunakan -1 pada proses reshaping

In [39]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
arr = arr.reshape(2, 2, -1)

In [41]:
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
arr.shape

(2, 2, 2)

## Melakukan flattening pada array

In [43]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [44]:
arr = arr.reshape(-1)

In [45]:
print(arr)

[1 2 3 4 5 6 7 8]


In [46]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [47]:
arr = arr.flatten()

In [48]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


## Melakukan duplikasi pada array

In [49]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

In [50]:
arr[0] = 42

In [51]:
arr

array([42,  2,  3,  4,  5])

In [52]:
x

array([1, 2, 3, 4, 5])

In [53]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

In [54]:
arr[0] = 42

In [55]:
arr

array([42,  2,  3,  4,  5])

In [56]:
x

array([42,  2,  3,  4,  5])