## Operation Iterasi 

In [133]:
import numpy as np

In [134]:
arr = np.array([1, 2, 3, 4, 5])

In [135]:
for x in arr:
    print(x)

1
2
3
4
5


## Iterasi numpy array 2d

In [136]:
arr = np.array([[1, 2, 3, ], [4, 5, 6]])

In [137]:
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


## Iterasi Numpy Array 3D

In [138]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10,11,12]]])

In [139]:
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Itersi dengan nditer

In [140]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])

In [141]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterasi dengan ndunumerate() pada Array 1D

In [142]:
arr = np.array([1, 2, 3])

In [143]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


## Iterasi dengan ndenumerate() pada Array 2D

In [144]:
arr = np.array([[1, 2, 3, ], [4, 5, 6]])

In [145]:
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


## Join terhadap 2 Array 1D

In [146]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [147]:
arr = np.concatenate((arr1, arr2))

In [148]:
print(arr)

[1 2 3 4 5 6]


## Join terhadap 2 Array 2D

In [149]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [150]:
arr = np.concatenate((arr1, arr2))

In [151]:
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [152]:
arr.shape

(4, 2)

In [153]:
arr = np.concatenate((arr1, arr2), axis=1)

In [154]:
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [155]:
arr.shape

(2, 4)

## Stack terhadap 2 Array 1D

In [156]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [157]:
arr = np.stack((arr1, arr2))

In [158]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [159]:
arr.shape

(2, 3)

## Stack terhadap 2 Array 1D menggunakan hstack()

In [160]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [161]:
arr = np.hstack((arr1, arr2))

In [162]:
print(arr)

[1 2 3 4 5 6]


## Stack terhadap 2 Array 1D menggunakan vstack()

In [163]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [164]:
arr = np.vstack((arr1, arr2))

In [165]:
print(arr)

[[1 2 3]
 [4 5 6]]


## Split terhdap 1 Array 1D

In [166]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [167]:
arr = np.array_split(arr, 3)

In [168]:
arr

[array([1, 2]), array([3, 4]), array([5, 6])]

## Split terhdap Array 2D

In [169]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

In [170]:
arr = np.array_split(arr, 3, axis=0)

In [171]:
arr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

## Search pada array 1D

In [172]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [174]:
x = np.where(arr == 4)

In [175]:
print(x)

(array([3, 5, 6], dtype=int64),)


In [176]:
x = np.where(arr**2 == 4)

In [177]:
print(x)

(array([1], dtype=int64),)


## Sort pada Array 1D

In [178]:
arr = np.array([3, 2, 0, 1])

In [179]:
print(np.sort(arr))

[0 1 2 3]


In [180]:
arr = np.array(['pisang', 'melon', 'apple'])

In [181]:
print(np.sort(arr))

['apple' 'melon' 'pisang']


## Sort pada Array 2D

In [184]:
arr = np.array([[3, 1, 8], [2, 1, 10]])

In [185]:
print(np.sort(arr))

[[ 1  3  8]
 [ 1  2 10]]
