## Filter pada Numpy Array 1D

In [41]:
import numpy as np

In [42]:
arr = np.array([41, 42, 43, 44])

In [43]:
x = [True, False, True, False]

In [44]:
arr = arr[x]

In [45]:
arr

array([41, 43])

In [46]:
arr = np.array([41, 42, 43, 44])

In [47]:
filter_arr = arr > 42

In [48]:
filter_arr

array([False, False,  True,  True])

In [49]:
arr = arr[filter_arr]

In [50]:
arr

array([43, 44])

In [51]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [52]:
filter_arr = arr % 2 == 0

In [53]:
arr = arr[filter_arr]

In [54]:
arr

array([2, 4, 6])

## Filter pada Numpy Array 1D menggunakan lebih dari 1 kondisi

In [55]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [56]:
filter_arr = (arr % 2 == 0) & (arr > 2)

In [57]:
arr = arr[filter_arr]

In [58]:
arr

array([4, 6])

## Filter pada Numpy Array 2D

In [59]:
arr = np.array([['1', 'one'],
                ['2', 'two'],
                ['3', 'three'],
                ['4', 'four'],
                ['5', 'five']])

In [60]:
arr.shape

(5, 2)

In [61]:
filter_arr = np.array(['two', 'four'])

In [62]:
arr = arr[np.in1d(arr[:, 1], filter_arr)]

In [63]:
arr

array([['2', 'two'],
       ['4', 'four']], dtype='<U5')