## Mendapatkan nilai integer secara random

In [18]:
import numpy as np
from numpy import random

In [19]:
x = random.randint(100)

In [20]:
x

60

## Mendapatkan nilai float secara random

In [21]:
x = random.rand()

In [22]:
x

0.5387194203592517

## Membuat array 1D dengan nilai integer secara Random

In [23]:
x = random.randint(100, size=(3, 5, 10))

In [24]:
x

array([[[13, 85,  9, 24, 31, 44,  0, 28, 23, 20],
        [50, 81, 73, 88, 49, 44, 74, 91, 17, 50],
        [72, 30, 90, 96, 15, 23, 33, 51,  3, 13],
        [81, 96, 76, 74, 70, 41, 13, 22, 71, 56],
        [84, 15,  3, 76, 26, 10, 53, 94, 36, 78]],

       [[82, 94, 48, 84, 13, 84, 36, 98, 89, 69],
        [76, 13, 67, 16, 34, 75, 34,  1, 11, 87],
        [94, 38, 83,  9, 73, 86, 30, 86,  1, 66],
        [96, 72,  6, 77, 84, 67, 18, 90,  0, 21],
        [20, 68, 29,  8, 52,  0, 86, 28, 69, 16]],

       [[32, 11, 74, 84, 90, 99, 46, 61, 78, 98],
        [59, 94, 86, 78, 32,  4, 83, 12,  3, 63],
        [54, 92, 97,  6, 12, 79, 73, 90, 99, 78],
        [58, 27, 56, 72, 44, 31, 32, 99,  1, 65],
        [33, 66, 81, 53,  7, 53, 33, 76, 14, 79]]])

## Membuat Array 1D dengan nilai float secara Random

In [26]:
x = random.rand(5)

In [27]:
x

array([0.12800615, 0.346973  , 0.25778886, 0.17634222, 0.62680066])

## Membuat Array 2D dengan nilai float secara Random

In [28]:
x = random.rand(3, 5)

In [29]:
x

array([[0.02468359, 0.94654604, 0.0070954 , 0.0731837 , 0.14980122],
       [0.18952708, 0.71569488, 0.78976309, 0.10404431, 0.27562455],
       [0.70192149, 0.98794756, 0.76116573, 0.20616577, 0.21103942]])

## Membuat nilai Integer random dari Array 1D

In [30]:
x = random.choice([3, 5, 8, 1, 2])

In [31]:
x

8

## Mengacak nilai yang ada pada array 1D

In [32]:
arr = np.array([1, 2, 3, 4, 5])

In [33]:
random.shuffle(arr)

In [34]:
arr

array([1, 3, 5, 4, 2])